version: '3'

services:
  webapp:
    container_name: main-app
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    env_file:
      - ../.env
    environment:
      - DEV_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@dev_database:5432/${POSTGRES_DB}
    ports:
      # - Host-Port:Contaier-Port
      - '5000:5000'
    links:
      - dev_db
    depends_on:
      - dev_db
    volumes:
      - api:/app/
    networks:
      - backend
    hostname: app_server

  dev_db:
    container_name: dev_database
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - ../.env
    networks:
      - backend
    volumes:
      - database_postgres:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge
volumes:
  api:
  database_postgres: